### ISSUE TITLE
Application is not running after transferring through bootloader

### ISSUE THREAD

**Issue by embhobbb** [ferenc-nemeth/stm32-bootloader#7]
Hi
I have done the changes as per and flash the code. I could see that application got transferred but application was not running. Application was just kled blinking.
here is both the code. 

[worksspace.zip](https://github.com/ferenc-nemeth/stm32-bootloader/files/6331364/worksspace.zip)

**Comment by ferenc-nemeth** [comment]
Hi,

What exactly happens when you jump to the application? Do you have a hard fault?

**Comment by Sergey-engineer-rus** [comment]
Hello!
I had the same problem.
It was fixed by adding HAL_RCC_DeInit (); before HAL_DeInit (); in the flash_jump_to_app(); function.

I also want to say that you can debug your application that used the bootloader:
Just start debugging on your application project (I am using IAR) and set a breakpoint on startup (main () function). Then press the RESET button on your device. After that, the bootloader will start and run your application, and the breakpoint will hit. Then you can see what is wrong.
For example, I see that RCC cannot be started in my application. So I added HAL_DeInit (); function in the bootloader.

Hope this information was helpful to you.

**Comment by ferenc-nemeth** [comment]
Hi Sergey,

Thank you for helping Embhobbb out.
